### ISSUE TITLE
Reduce startup noise

### ISSUE THREAD

**Issue by Nix-Starlight** [CoagulateSL/GPHUD#101]
[13:42] GPHUD: GPHUD HUD 3.11.0 Apr  2 2021 (C) Iain Maltz (iain.maltz) / Iain Price, Coagulate
[13:42] GPHUD: GPHUD Stack 3.19.15 2022-03-23 19:13 (C) Iain Maltz (iain.maltz) / Iain Price, Coagulate Release Notes
[13:42] GPHUD: You have 0 points available to spend. 

I want to be able to disable these from showing up when the player logs in. It spams local chat a bit and isn't necessary.

**Comment by iprice** [comment]
Won't happen.

I'm prepared to reduce the banner to one line, and remove the zero points thing if its zero.

I've had issues with a previous product with people claiming that the product is in some way "exclusive" to them or their property ; the banner makes it pretty easy for almost anyone to dispute that and contact the actual code owner directly.

**Comment by iprice** [comment]
Also probably how I get most of my custom :P

**Comment by Nix-Starlight** [comment]
> Won't happen.
> 
> I'm prepared to reduce the banner to one line, and remove the zero points thing if its zero.
> 
> I've had issues with a previous product with people claiming that the product is in some way "exclusive" to them or their property ; the banner makes it pretty easy for almost anyone to dispute that and contact the actual code owner directly.

I'm fine with a single line! It just gets annoying. A single line is a huge step ahead.
