### ISSUE TITLE
Make menus support a variable description text

### ISSUE THREAD

**Issue by Nix-Starlight** [CoagulateSL/GPHUD#102]
When you open a menu it says "Choice of menu item" I want to be able to change what that says. Maybe an explanation of what each button does? Like a simple button with limited letters doesn't explain much. Especially when players need to spend ability points and have no idea what each one does.

**Comment by iprice** [comment]
Funny how long this has been around for.  I think menus even ask for a description when you create them, and then never use it for anything.

**Comment by Nix-Starlight** [comment]
> Funny how long this has been around for. I think menus even ask for a description when you create them, and then never use it for anything.

In order to use the description field, I'd have to delete the menu and recreate it. Also was unaware that the description field changed that specific text.

**Comment by Nix-Starlight** [comment]
I tried once again to use the description field. It did nothing to the menu in world.
