### ISSUE TITLE
More flexible RNG

### ISSUE THREAD

**Issue by ronlaws86** [CoagulateSL/GPHUD#229]
**Is your feature request related to a problem? Please describe.**

Ability to adjust the algorithm behind gsRand() or a new function like gsSeededRand() with additional paramiters to allow you to adjust the bias or seed. 
**Describe the solution you'd like**
A new function for more flexible RNG or the ability to adjust the RNG like we had in the old RP HUD
If like the old HUD a page where admins can adjust the math/seeding etc. behind the RNG globally

If int he case of a function, a function similar to gsRand but it takes more arguments allowing you to set more paramiters on call e.g.
gsSeededRand(seed, low, high);  etc.

**Describe alternatives you've considered**
Have tried making a custom RNG but due to the limitations of GS Script and the low execution cap this is  not possible with current functions available.

**Additional context**

The current gsRand function is 'okay' in most cases, but there are some cases where you may want to create a 50/50 chance, however the reality of it is that there appears to be a bias in the RNG that will turn a 50/50 in to a 1 in 8 chance which has been generating a lot of complaints from players.

**Comment by iprice** [comment]
I don't find any basis for this assertion.  Go to scripting and create the following script:

`Integer  zeros=0;
Integer ones=0;
while (1) {
  Integer  rand=gsRand(0,1);
  if (rand==0) { zeros=zeros+1; }
  else { ones=ones+1; }
}
`

Hit the "View Results" page on the scripting page, this will show the distribution of ones and zeroes, which will vary a lot but average out over time.  Sample runs

ones	Integer	139
zeros	Integer	162

ones	Integer	153
zeros	Integer	149

ones	Integer	139
zeros	Integer	162

ones	Integer	156
zeros	Integer	146

ones	Integer	155
zeros	Integer	147

I see no issue with these results.  Please produce a sample script that highlights this bias.

For completeness, the gsRand function's implementation can be found here:
https://github.com/CoagulateSL/GPHUD/blob/master/src/net/coagulate/GPHUD/Modules/Scripting/Language/Functions/Randomness.java#L26
The generating method used is ThreadLocalRandom from java https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadLocalRandom.html

**Comment by iprice** [comment]
Upped the sample size on my dev box as ya know the more samples the better the test, some results here:

ones	Integer	151319
zeros	Integer	151699

ones	Integer	151104
zeros	Integer	151901

ones	Integer	151391
zeros	Integer	151631

ones	Integer	151666
zeros	Integer	151372

ones	Integer	151546
zeros	Integer	151485

**Comment by dazedwolf** [comment]
I used the gsRand(1,100) to run 2600 1d100's and outputted it into a csv, then made it into a normal graph: 

![image](https://user-images.githubusercontent.com/82187107/228073299-b7cec920-292b-4268-8599-af667f514291.png)

It came out fairly random from my tests.
