### ISSUE TITLE
gsSetMap unexpectedly returns 0 length?

### ISSUE THREAD

**Issue by justcfx2u** [CoagulateSL/GPHUD#24]
**Describe the bug**
**`gsSetMap`** appears to return 0 elements instead of returning the Set in List format.

**To Reproduce**
1. Create SET on Characters named Skills
2. Populate Skills with a few entries + quantities (e.g., 5xFirearms, 5xFirst Aid, 1xGunnery) [[Example Screenshot]](https://i.gyazo.com/62dc151d162b7e10b008abb9c4390bbb.png)
3. Create script Test:

```
List skills = gsSetMap(CALLER, "Skills");
_ = gsSayAsHUDIfOnline(CALLER, skills[0]);
```

4. Execute script, receive error: `/1 Scripting.Test`
*Script error: {GSArrayIndexOutOfBoundsException} List skills is 0 long but requested access to element 0 at Test row 2, column 32, PC=115, OP=19 (LoadIndexed)*

**Expected behavior**
Script prints label of first skill.

**Actual behavior**
Script returns error message.

**Error Message**
*Script error: {GSArrayIndexOutOfBoundsException} List skills is 0 long but requested access to element 0 at Test row 2, column 32, PC=115, OP=19 (LoadIndexed)*

**Additional context**

**`gsSetList`** works fine, but lacks quantities of **`getSetMap`**.
```
List skills = gsSetList(CALLER, "Skills");
_ = gsSayAsHUDIfOnline(CALLER, skills[0]);
```
The `gsSetList` variant returns "Firearms" as expected.

**Comment by iprice** [comment]
Confirmed, it always returns an empty list.

**Comment by iprice** [comment]
Fix should now be live (hotfixed)
