### ISSUE TITLE
Configuration.setChar no longer accepting blank values and fails silently.

### ISSUE THREAD

**Issue by ronlaws86** [CoagulateSL/GPHUD#266]
**Describe the bug**
Function to set KV's is no longer taking blank values (Which is often their default state)

**To Reproduce**
Set the KV from it's default state (blank) to any value, then try to blank it again.

String KV = gsGetKV(CALLER,"Characters.NameOfKV");
String ValToWrite = ""; 

gsSayToChar(CALLER,"KV Reads: "+KV );
gsSayToChar(CALLER,"Attempting to write '"+ValToWrite+"'");

gsElevatedAPI(CALLER,"Configuration.setChar",[CALLER,"Characters.NameOfKV",ValToWrite]);

KV = gsGetKV(CALLER,"Characters.NameOfKV");
gsSayToChar(CALLER,"KV Now Reads: '"+KV +"'");

**Expected behavior**
The KV to be blanked

**Error Message**
None, it just doesn't write the null value.

**Additional context**
Some scripts may well look for null values and take them as their default or unset state, this was the previous behavour before a recent update, and they could be reliably blanked beforehand, but now setting them to blank no longer works, and the function fails silently.

**Comment by iprice** [comment]
Good catch, added a unit test for this in #267 and fixed in #268 hopefully
