### ISSUE TITLE
Currency base coin Long Name not saving

### ISSUE THREAD

**Issue by Trinket-OS** [CoagulateSL/GPHUD#270]
**Describe the bug**
Within the Currency module, the Long Name of the Base Currency is no longer saving and only the Short Name is saving or being used.

**To Reproduce**
1. Go to GPHUD Website and log in. On left hand menu, choose "Configuration" and then "Currency"
2.  Presuming that you have already created at least one form of currency: Click on that currency in order to edit it
3. On the Currency Configuration screen there will be a button called "Rename Base Coin" Clicking it will bring you to a screen where you can choose the Long Name and Short Name of the currency to be modified. 
4. Enter both a Long name and a Short name and click Submit. Example: Choose "Copper" as the long name and "C" as the short name
5. Returning to the Currency Configuration screen it will display only the Short name on the results, omitting the Long Name.
6. Note that this only seems to apply to the Base Coin and any additional coins added into the currency in the second section retain both their long and short names.

**Expected behavior**
The Short and Long names should be retained, as these are recognized by the system for currency transfers between players. Players can enter "1c" or "1 copper" as values in the transaction function. With this not retaining the long name it's stopped working with that alias.

**Error Message**
If an error message is generated, copy paste it here.
No actual error message

**Additional context**
Here is a gyazo video of me demonstrating the problem live, it takes only a few seconds
https://gyazo.com/6f3756c3cc7ff8b7299f90d956fd7af7

**Comment by iprice** [comment]
Added unit test, confirmed and resolved, was due to accidentally sharing a cache used for short/long names of base coins.
