### ISSUE TITLE
gsDefined() / if(var != null)  ??

### ISSUE THREAD

**Issue by ronlaws86** [CoagulateSL/GPHUD#66]
**Is your feature request related to a problem? Please describe.**
A Function that can be used to test whether a variable has been declared/defined within the scope, similar to PHP's isset or defeined(): function 

**Describe the solution you'd like**
A function (or documented method) to test if a variable exists, in Java for example you would do 
if (var != null) {
    //var exists
} else {
   //var does not exist
}

**Describe alternatives you've considered**
I have tried the above method from Java with no success
net.coagulate.GPHUD.Modules.Scripting.Language.GSUnknownIdentifier - Variable var is not defined

**Additional context**
It would be very useful to have this functionality in some form to allow for 'fallback' or 'failsafe' cases, also useful for general testing

**Comment by iprice** [comment]
https://sl.coagulate.net/GPHUD/introspection/gsfunctions/gsDefined
